# Generated by Django 5.2.3 on 2025-09-15 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(default='Véhicule', max_length=100)),
                ('driver_name', models.CharField(default='Conducteur', max_length=100)),
                ('alert_type', models.CharField(choices=[('drowsiness', 'Somnolence'), ('fatigue', 'Fatigue'), ('speeding', 'Excès de vitesse'), ('harsh_braking', 'Freinage brusque'), ('harsh_acceleration', 'Accélération brusque'), ('route_deviation', 'Déviation de route'), ('vehicle_breakdown', 'Panne véhicule'), ('emergency', 'Urgence')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Modéré'), ('high', 'Élevé'), ('critical', 'Critique')], max_length=10)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('acknowledged', 'Accusé réception'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('dismissed', 'Rejeté')], default='new', max_length=20)),
                ('message', models.TextField()),
                ('location_latitude', models.FloatField(blank=True, null=True)),
                ('location_longitude', models.FloatField(blank=True, null=True)),
                ('speed_at_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('arduino_data', models.JSONField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
