# Generated by Django 4.2.7 on 2025-09-13 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('minibus', 'Minibus'), ('car', 'Voiture'), ('van', 'Van')], max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Actif'), ('maintenance', 'En maintenance'), ('out_of_service', 'Hors service')], default='active', max_length=20)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_entertainment', models.BooleanField(default=False)),
                ('arduino_device_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField()),
                ('fuel_level', models.FloatField(blank=True, null=True)),
                ('engine_temperature', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_data', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
