# Generated by Django 5.2.3 on 2025-09-14 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_set_client_default'),
        ('travel', '0002_somnolencealert'),
    ]

    operations = [
    ]
