# Generated by Django 5.2.3 on 2025-09-14 20:56

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_merge_0002_set_client_default_0002_somnolencealert'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('travel.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AlterModelOptions(
            name='somnolencealert',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Alerte de somnolence', 'verbose_name_plural': 'Alertes de somnolence'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['date', 'departure_time'], 'verbose_name': 'Voyage', 'verbose_name_plural': 'Voyages'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='card_brand',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='card_last4',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='somnolencealert',
            name='raw',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(default='TMP-REF', max_length=20, unique=True, verbose_name='Référence de réservation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name="Raison d'annulation"),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Réduction appliquée (%)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(default='Passager', max_length=200, verbose_name='Nom du passager'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_phone',
            field=models.CharField(default='N/A', max_length=20, verbose_name='Téléphone du passager'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('wave', 'Wave'), ('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('credit_card', 'Carte bancaire')], max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de paiement'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence de paiement'),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_numbers',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéros de siège'),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, verbose_name='Demandes spéciales'),
        ),
        migrations.AddField(
            model_name='booking',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire'),
        ),
        migrations.AddField(
            model_name='bus',
            name='arduino_device_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_buses', to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur assigné'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='somnolencealert',
            name='action_taken',
            field=models.TextField(blank=True, verbose_name='Action prise'),
        ),
        migrations.AddField(
            model_name='somnolencealert',
            name='alert_id',
            field=models.CharField(default='TMP-ALERT', max_length=50, unique=True, verbose_name="ID d'alerte"),
        ),
        migrations.AddField(
            model_name='somnolencealert',
            name='arduino_device_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID du dispositif Arduino'),
        ),
        migrations.AddField(
            model_name='somnolencealert',
            name='escalated',
            field=models.BooleanField(default=False, verbose_name='Escaladée'),
        ),
        migrations.AddField(
            model_name='somnolencealert',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Escaladée vers'),
        ),
        migrations.AddField(
            model_name='somnolencealert',
            name='follow_up_required',
            field=models.BooleanField(default=False, verbose_name='Suivi requis'),
        ),
        migrations.AddField(
            model_name='somnolencealert',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Traitée le'),
        ),
        migrations.AddField(
            model_name='somnolencealert',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Traitée par'),
        ),
        migrations.AddField(
            model_name='somnolencealert',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='somnolencealert',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='somnolencealert',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='somnolencealert',
            name='raw_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Données brutes'),
        ),
        migrations.AddField(
            model_name='somnolencealert',
            name='sensor_confidence',
            field=models.FloatField(default=0.0, verbose_name='Confiance du capteur'),
        ),
        migrations.AddField(
            model_name='somnolencealert',
            name='severity',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], default='medium', max_length=20, verbose_name='Sévérité'),
        ),
        migrations.AddField(
            model_name='somnolencealert',
            name='status',
            field=models.CharField(choices=[('new', 'Nouvelle'), ('acknowledged', 'Accusée'), ('investigating', 'En cours de traitement'), ('resolved', 'Résolue'), ('false_positive', 'Fausse alerte')], default='new', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='somnolencealert',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.trip', verbose_name='Voyage'),
        ),
        migrations.AddField(
            model_name='trip',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'arrivée"),
        ),
        migrations.AddField(
            model_name='trip',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée"),
        ),
        migrations.AddField(
            model_name='trip',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Réduction (%)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_as_driver', to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur'),
        ),
        migrations.AddField(
            model_name='trip',
            name='max_seats',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Places maximum'),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('programmed', 'Programmé'), ('boarding', 'Embarquement'), ('in_transit', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('delayed', 'Retardé')], default='programmed', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_number',
            field=models.CharField(default='TMP-TRIP', max_length=20, unique=True, verbose_name='Numéro de voyage'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('one_way', 'Aller simple'), ('round_trip', 'Aller-retour'), ('recurring', 'Régulier')], default='one_way', max_length=20, verbose_name='Type de voyage'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Annulé le'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_email',
            field=models.EmailField(max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de places'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('partially_paid', 'Partiellement payée'), ('paid', 'Payée'), ('validated', 'Validée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée'), ('no_show', 'Absent')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ticket_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numéro de ticket'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='travel.trip', verbose_name='Voyage'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(choices=[('aller', 'Aller Simple'), ('retour', 'Aller-Retour')], max_length=10, verbose_name='Type de voyage'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validé le'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_model',
            field=models.CharField(max_length=100, verbose_name='Modèle'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Numéro du bus'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_route', 'En Route'), ('maintenance', 'En Maintenance'), ('hors_service', 'Hors Service'), ('en_panne', 'En Panne')], default='disponible', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='total_seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de places'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('client', 'Client'), ('driver', 'Chauffeur')], default='client', max_length=10),
        ),
        migrations.AlterField(
            model_name='somnolencealert',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.bus', verbose_name='Bus'),
        ),
        migrations.AlterField(
            model_name='somnolencealert',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur'),
        ),
        migrations.AlterField(
            model_name='somnolencealert',
            name='duration_seconds',
            field=models.FloatField(verbose_name='Durée (secondes)'),
        ),
        migrations.AlterField(
            model_name='somnolencealert',
            name='handled',
            field=models.BooleanField(default=False, verbose_name='Traitée'),
        ),
        migrations.AlterField(
            model_name='somnolencealert',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Horodatage'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='arrival_city',
            field=models.CharField(max_length=100, verbose_name="Ville d'arrivée"),
        ),
        migrations.AlterField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.bus', verbose_name='Bus assigné'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(verbose_name='Date de départ'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_city',
            field=models.CharField(max_length=100, verbose_name='Ville de départ'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.TimeField(verbose_name='Heure de départ'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Durée estimée'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_return',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix aller-retour'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_simple',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix aller simple'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
