# Generated by Django 5.2.3 on 2025-09-15 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_driverprofile_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de taxe (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant de taxe')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Stripe Payment Intent')),
                ('stripe_payment_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Statut paiement Stripe')),
                ('billing_name', models.CharField(max_length=200, verbose_name='Nom de facturation')),
                ('billing_email', models.EmailField(max_length=254, verbose_name='Email de facturation')),
                ('billing_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone de facturation')),
                ('billing_address', models.TextField(blank=True, verbose_name='Adresse de facturation')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdf/', verbose_name='Fichier PDF')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='travel.booking', verbose_name='Réservation')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-issue_date'],
            },
        ),
    ]
